# Uncomment the next line to define a global platform for your project
  platform :ios, "11.0"

target 'iOSRecruitingBrazil' do
  use_frameworks!

  # Commom
  pod "Alamofire"
  pod "SwiftyJSON", '~> 4.0'

end